sudo: false

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache
  - $HOME/.pip-cache

language: python
python:
  # - "3.6"
  # - "3.7"
  - "3.8"

branches:
  only:
    - master
    - develop

# matrix:
#   include:     
#     - name: "Python 3.8.0 on macOS"
#       os: osx
#       osx_image: xcode11.2
#       language: shell

install: 
  - sudo apt-get install build-essential python-dev python3-pip
  - pip3 install -U pip coveralls
  - pip3 install -U psutil cython numpy
  - pip3 install .

script:
  coverage run --source fse setup.py test

after_success:
  coveralls
